global.params.x=999
global.params.y=888

spring.datasource.url= jdbc:h2:mem:customer-db
spring.h2.console.enabled=true

spring.cloud.discovery.enabled=true

eureka.instance.hostname=${DOCKER_HOST_NAME:$HOSTNAME}

spring.cloud.config.enabled=true

spring.data.rest.base-path=/api

management.endpoints.web.exposure.include=*